name: AWAM
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.5.0=h27087fc_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.6=hef167b5_0
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.1=py38h06a4308_0
  - cpython=3.8.20=py38hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - esmf=8.7.0=mpi_mpich_h2e66f26_100
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5888daf_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - filelock=3.16.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.7.9=hb077bed_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.14.4=mpi_mpich_h7f58efa_1
  - icu=75.1=he02047a_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.28.0=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.1.7=0
  - libcurand=10.3.6.82=0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.12=h166bdaf_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - libnetcdf=4.9.2=mpi_mpich_h1ab6521_15
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpnetcdf=1.13.0=mpi_mpich_hdce4f7b_101
  - libpng=1.6.44=hadc24fc_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.4.0=hc85c160_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzip=1.11.1=hf83b1b0_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.2.0=py38hab2c0dc_1
  - mkl_random=1.2.0=py38hc5bc63f_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0.1=mpich
  - mpich=4.2.3=h670b19f_100
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=py38h06a4308_0
  - netcdf-fortran=4.6.1=mpi_mpich_h147b545_7
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.1=py38h06a4308_0
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.3.2=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - parallelio=2.6.3=mpi_mpich_h43d51f9_100
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38h0ee0e06_1
  - pip=24.0=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=h4a871b0_2_cpython
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python_abi=3.8=5_cp38
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=ha2e4443_0
  - sqlite=3.47.0=h9eae976_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=2.2.2=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py38h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - apache-beam==2.60.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==24.2.0
      - axial-positional-embedding==0.3.5
      - bokeh==3.1.1
      - cdsapi==0.7.5
      - certifi==2024.8.30
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - colt5-attention==0.11.1
      - contourpy==1.1.1
      - crcmod==1.7
      - cycler==0.12.1
      - dask==2023.5.0
      - datapi==0.1.1
      - dill==0.3.1.1
      - dnspython==2.6.1
      - docopt==0.6.2
      - einops==0.8.0
      - fastavro==1.9.7
      - fasteners==0.19
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - grpcio==1.65.5
      - h5py==3.11.0
      - hdfs==2.7.3
      - httplib2==0.22.0
      - imageio==2.35.1
      - immutabledict==4.2.1
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - jsonpickle==3.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - local-attention==1.10.0
      - locket==1.0.0
      - matplotlib==3.7.5
      - multiurl==0.3.3
      - mypy-extensions==1.0.0
      - netcdf4==1.6.4
      - numcodecs==0.12.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - objsize==0.7.0
      - opencv-python==4.10.0.84
      - orjson==3.10.12
      - pandas==2.0.3
      - partd==1.4.1
      - patool==1.12
      - pkgutil-resolve-name==1.3.10
      - product-key-memory==0.2.11
      - proto-plus==1.25.0
      - protobuf==4.25.5
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pydot==1.4.2
      - pymongo==4.10.1
      - pyparsing==3.1.4
      - pytz==2024.2
      - pywavelets==1.4.1
      - rechunker==0.5.2
      - redis==5.2.0
      - referencing==0.35.1
      - reformer-pytorch==1.4.4
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.20.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scikit-base==0.7.8
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sktime==0.29.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.3.2
      - toolz==1.0.0
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.0
      - triton==3.0.0
      - tzdata==2024.2
      - xarray==2023.1.0
      - xarray-beam==0.6.3
      - xyzservices==2024.9.0
      - zarr==2.16.1
      - zstandard==0.23.0
